load ../assumptions.maude

fmod TEST is  
    protecting MATRIX-ASSUMPTIONS .  
    ops X Y : -> MatrixSymbol .
endfm 

red in TEST : X is symmetric , Y is symmetric => X Y is symmetric .
red in TEST : X is symmetric => transpose(X) is symmetric .
red in TEST : no-knowledge => X transpose(X) is symmetric .
red in TEST : X is positive-definite => X is invertible .
red in TEST : X is orthogonal , Y is invertible => X Y is invertible .
red in TEST : no-knowledge => X transpose(X) is symmetric .
red in TEST : X is invertible => X transpose(X) is positive-definite .

red in TEST : X is invertible , Y is invertible => X Y is invertible .
