load ../assumptions.maude

fmod TEST is  
    protecting MATRIX-ASSUMPTIONS .  
    ops A B X Y : -> MatrixSymbol .
    op n : -> Int .
    eq A = matrix('A , n by n) .
    eq B = matrix('B , n by n) .
endfm 

red in TEST : X is symmetric , Y is symmetric => X Y is symmetric .
red in TEST : X is symmetric => transpose(X) is symmetric .
red in TEST : no-knowledge => X transpose(X) is symmetric .
red in TEST : A is positive-definite => A is invertible .
red in TEST : A is orthogonal , B is invertible => A B is invertible .
red in TEST : no-knowledge => X transpose(X) is symmetric .
red in TEST : A is invertible => A transpose(A) is positive-definite .
red in TEST : A is invertible , B is invertible => A B is invertible .

red in TEST : A is symmetric , A is positive-definite , B is orthogonal 
           => B A transpose(B) is symmetric , 
              B A transpose(B) is positive-definite .
red in TEST : A is diagonal => A is triangular .

red in TEST : A is diagonal => A is upper-triangular , A is lower-triangular .
red in TEST : A is lower-triangular => transpose(A) is upper-triangular .
