load ../gemm.maude
load ../symm.maude
load ../trsm.maude
load ../../compute-graph.maude

mod INTEGRATION-TEST is 
    protecting GEMM .
    protecting SYMM .
    protecting TRSM .
    protecting COMPUTE-TEST .
    var comp : Computation .
endm

search [10, 10] in INTEGRATION-TEST : 
        compute(v, X \ a (Z Y + X) with X is lower-triangular , Y is symmetric)
        =>! comp such that valid(comp) .
