load ../symm.maude

mod SYMM-TEST is 
    protecting COMPUTE-SYMM .
    protecting COMPUTE-TEST .
    var comp : Computation .
endm

search [10, 10] in SYMM-TEST : compute(v, a X Y + b Z with X is symmetric)
        =>! comp such that valid(comp) .
search [10, 10] in SYMM-TEST : compute(v, a X Y + b Z with Y is symmetric)
        =>! comp such that valid(comp) .
search [10, 10] in SYMM-TEST : compute(v, a X Y + b Z with no-knowledge)
        =>! comp such that valid(comp) .
