load ../trsm.maude

mod TRSM-TEST is 
    protecting TRSM .
    protecting COMPUTE-TEST .
    var comp : Computation .
    var b : Bool .
endm

search [10, 10] in TRSM-TEST : compute(v, X \ (a Y) with X is lower-triangular)
        =>! comp such that valid(comp) .

search [10, 10] in TRSM-TEST : compute(v, transpose(X) \ a Y 
            with X is lower-triangular)
            =>! comp such that valid(comp).
search [10, 10] in TRSM-TEST : compute(v, transpose(X) \ a Y 
            with X is upper-triangular)
            =>! comp such that valid(comp) .
search [10, 10] in TRSM-TEST : compute(v, X \ a Y with X is unit-triangular)
        =>! comp such that valid(comp) .
